name: Generate Tags

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with: 
          fetch-depth: '0'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: set-up git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Run Script
        run: |
          pip install requests
          python .github/scripts/main.py
